// projects_data.js — generated by admin panel
// Replace this file then push to GitHub.

const PROJECTS = {
  "work": [
    {
      "title": "KJO Executive Energy Management Report",
      "year": "2024",
      "titleSize": "1.15rem",
      "bodySize": "0.86rem",
      "desc": "Compiled and analysed HVAC power consumption data across 29 KJO community buildings. Produced an 11-slide executive presentation and a formal cover letter to the Executive Director of Operations, identifying demand reduction opportunities and quantified cost saving targets.",
      "tags": ["Energy Management", "HVAC", "Power Analysis", "MS Office", "KJO"],
      "imgs": [],
      "img": ""
    },
    {
      "title": "UTP / FOC Network Infrastructure Rollout",
      "year": "2022 – Present",
      "titleSize": "1.15rem",
      "bodySize": "0.86rem",
      "desc": "Full-scope network cabling projects within KJO facilities — planning cable routes, pulling and terminating UTP Cat6 and fibre optic cables, testing with Fluke equipment, and commissioning structured cabling systems across multiple buildings.",
      "tags": ["FOC", "UTP Cat6", "Structured Cabling", "Commissioning", "KJO"],
      "imgs": [],
      "img": ""
    },
    {
      "title": "Automatic Door Control System Overhaul",
      "year": "2023",
      "titleSize": "1.15rem",
      "bodySize": "0.86rem",
      "desc": "Supervised corrective and preventive maintenance on automatic, sliding, and rotating door control systems across the KJO community. Diagnosed control board faults, replaced defective actuators and sensors.",
      "tags": ["Control Systems", "Fault Diagnosis", "Maintenance", "KJO"],
      "imgs": [],
      "img": ""
    },
    {
      "title": "IoT Facility Monitoring System",
      "year": "2019 – 2021",
      "titleSize": "1.15rem",
      "bodySize": "0.86rem",
      "desc": "MSc thesis at Politecnico di Torino. Designed and deployed the sensor and data collection layer — ESP8266/ESP32 nodes via MQTT to Raspberry Pi, through Node-RED into MySQL. Dataset used by a separate team for BIM integration research.",
      "tags": ["IoT", "ESP32", "MQTT", "Node-RED", "MySQL", "Raspberry Pi", "PoliTO"],
      "imgs": [],
      "img": ""
    }
  ],
  "hobby": [
    {
      "title": "Raspberry Pi Digital Office Nameplate",
      "year": "2024",
      "titleSize": "1.15rem",
      "bodySize": "0.86rem",
      "desc": "Offline digital nameplate on Raspberry Pi 4 — Node.js/Express server, kiosk mode, multi-theme UI with Arabic support, Meeting Room mode with GPIO relay toggle. Custom blank cursor fix for Wayland/wayfire.",
      "tags": ["Raspberry Pi", "Node.js", "GPIO", "Kiosk", "Wayland", "Linux"],
      "imgs": [],
      "img": ""
    },
    {
      "title": "ESP32 Smart LED Lighting (WLED)",
      "year": "2024",
      "titleSize": "1.15rem",
      "bodySize": "0.86rem",
      "desc": "WS2813 LED strip system driven by ESP32 running WLED firmware. Proper level shifting, power injection, Home Assistant integration via MQTT. Clean enclosure with capacitors and correct wire gauges.",
      "tags": ["ESP32", "WS2813", "WLED", "Home Assistant", "MQTT"],
      "imgs": [],
      "img": ""
    },
    {
      "title": "Home Assistant via Cloudflare Tunnel",
      "year": "2025",
      "titleSize": "1.15rem",
      "bodySize": "0.86rem",
      "desc": "Secure remote access to Home Assistant on Raspberry Pi using Cloudflare Tunnel — zero open ports, automatic SSL, personal domain. Integrated with portfolio site on Cloudflare Pages.",
      "tags": ["Home Assistant", "Cloudflare", "Raspberry Pi", "Networking"],
      "imgs": [],
      "img": ""
    },
    {
      "title": "2DOF Motorised Gaming Motion Platform",
      "year": "2023 – Present",
      "titleSize": "1.15rem",
      "bodySize": "0.86rem",
      "desc": "Pitch + roll motion rig using four 12V linear actuators, Arduino Mega, and SimHub for telemetry-driven effects. Wooden/PVC frame with PS5/Xbox controllers mounted on the platform. Work in progress.",
      "tags": ["Arduino", "SimHub", "Linear Actuators", "Motion Platform", "12V"],
      "imgs": [],
      "img": ""
    }
  ]
};
