// projects_data.js — generated by admin panel
// Replace this file then push to GitHub.

const PROJECTS = {
  "work": [],
  "hobby": [
    {
      "title": "Raspberry Pi Digital Office Nameplate",
      "year": "2024",
      "titleSize": "1.15rem",
      "bodySize": "0.86rem",
      "desc": "Offline digital nameplate on Raspberry Pi 4 — Node.js/Express server, kiosk mode, multi-theme UI with Arabic support, Meeting Room mode with GPIO relay toggle. Custom blank cursor fix for Wayland/wayfire.",
      "tags": ["Raspberry Pi", "Node.js", "GPIO", "Kiosk", "Wayland", "Linux"],
      "imgs": [],
      "img": ""
    },
    {
      "title": "ESP32 Smart LED Lighting (WLED)",
      "year": "2024",
      "titleSize": "1.15rem",
      "bodySize": "0.86rem",
      "desc": "WS2813 LED strip system driven by ESP32 running WLED firmware. Proper level shifting, power injection, Home Assistant integration via MQTT. Clean enclosure with capacitors and correct wire gauges.",
      "tags": ["ESP32", "WS2813", "WLED", "Home Assistant", "MQTT"],
      "imgs": [],
      "img": ""
    },
    {
      "title": "Home Assistant via Cloudflare Tunnel",
      "year": "2025",
      "titleSize": "1.15rem",
      "bodySize": "0.86rem",
      "desc": "Secure remote access to Home Assistant on Raspberry Pi using Cloudflare Tunnel — zero open ports, automatic SSL, personal domain. Integrated with portfolio site on Cloudflare Pages.",
      "tags": ["Home Assistant", "Cloudflare", "Raspberry Pi", "Networking"],
      "imgs": [],
      "img": ""
    },
    {
      "title": "2DOF Motorised Gaming Motion Platform",
      "year": "2023 – Present",
      "titleSize": "1.15rem",
      "bodySize": "0.86rem",
      "desc": "Pitch + roll motion rig using four 12V linear actuators, Arduino Mega, and SimHub for telemetry-driven effects. Wooden/PVC frame with PS5/Xbox controllers mounted on the platform. Work in progress.",
      "tags": ["Arduino", "SimHub", "Linear Actuators", "Motion Platform", "12V"],
      "imgs": [],
      "img": ""
    }
  ]
};